investor/urls.py
from django.urls import path 
from . import views
app_name = 'investor'
urlpatterns = [
    path('investor/admin/login', views.admin_login, name="admin_login"),
    path('investor/admin/logout', views.admin_logout, name="admin_logout"), 
    path('dashboards/', views.dashboard, name='dashboard'),
    path('investor/signup',views.investor_registration, name='investor_registration'),
    path('',views.investor_login, name='investor_login'),
    path('investor/password-reset',views.investor_password_resets, name='investor_password_resets'),
    path('investor-account/<int:id>/active',views.investor_account_active, name='investor_account_active'),
    path('investor-password/<int:id>/reset',views.investor_password_reset_link, name='investor_password_reset_link'),
    path('investor/logout',views.investor_logout, name='investor_logout'),
    path('investor/request_to_invest/<int:id>/',views.request_to_invest, name='request_to_invest'),
    path('admin/approve/<int:id>/',views.approve_investment, name='approve_investment'),
    path('admin/cancle/<int:id>/',views.cancle_investment, name='cancle_investment'),
    path('admin/notifications/',views.admin_notification_list, name='admin_notification_list'),
    path('admin/notifications/unread',views.admin_unread_notifications, name='admin_unread_notifications'),
    path('admin/notifications/<int:id>/',views.investor_notification_list, name='investor_notification_list'),
    path('admin/notifications/unread/<int:id>/',views.investor_unread_notification_list, name='investor_unread_notification_list'),
    path('investor/notification/<int:id>/',views.single_nofication, name='single_nofication'),
    path('investor/notification/delete',views.ajax_notification_delete, name='ajax_notification_delete'),
    path('investor/notification/mark-read',views.ajax_notification_markas_read, name='ajax_notification_markas_read'),
    path('investor/<int:id>/terms-condition-pdf',views.terms_condition_pdf, name='terms_condition_pdf'),
    path('investor/investors/investors-list/',views.all_investor_list, name='all_investor_list'),
    path('investor/investor/<int:id>/delete',views.investor_delete, name='investor_delete'),
    path('investor/invests/all-pending-request',views.all_pending_request, name='all_pending_request'),
    path('investor/invests/all-active-invest-list',views.all_active_invest_list, name='all_active_invest_list'),
    path('investor/payments/upcoming-payment',views.upcoming_payment, name='upcoming_payment'),
    path('investor/admin-chat/<int:id>',views.admin_chat, name='admin_chat'),
    path('investor/investor-chat/<int:id>',views.investor_chat, name='investor_chat'),
    path('investor/make-payment/<int:id>',views.make_payment, name='make_payment'),
    path('investor/payments/interest-paid-admin',views.interest_paid_admin, name='interest_paid_admin'),
    path('investor/interest-paid/<int:id>/delete',views.interest_paid_admin_delete, name='interest_paid_admin_delete'),
    path('investor/dashboard/password/change',views.admin_password_change, name='admin_password_change'),
    path('investor/investors/add-investor/',views.add_new_investor, name='add_new_investor'),
    path('investor-active-link/<int:id>/activate',views.investor_active_link, name='investor_active_link'),
    path('investor/banks/add-bank',views.add_bank, name='add_bank'),
    path('investor/banks/bank-list',views.bank_list, name='bank_list'),
    path('investor/bank-list/<int:id>',views.bank_edit, name='bank_edit'),
    path('investor/bank-active/<int:id>',views.bank_active, name='bank_active'),
    path('investor/bank-deactive/<int:id>',views.bank_deactive, name='bank_deactive'),
    path('investor/password-change/<int:id>',views.investor_password_change, name='investor_password_change'),
    path('investor/profile-update/<int:id>',views.investor_profile_update, name='investor_profile_update'),
    path('investor/interest-received-investor/<int:id>',views.interest_received_investor, name='interest_received_investor'),
    path('investor/investor-active-invest/<int:id>',views.investor_active_invest, name='investor_active_invest'),
    path('investor/investor-pending-invest/<int:id>',views.investor_pending_invest, name='investor_pending_invest'),
    path('investor/investor-cancle-invest/<int:id>',views.investor_cancle_investment, name='investor_cancle_investment'),
    path('investor/popup/add-popup',views.add_popup, name='add_popup'),
    path('investor/popup/popup-list',views.popup_list, name='popup_list'),
    path('investor/popup/popup-edit/<int:id>',views.popup_edit, name='popup_edit'),
    path('investor/popup-delete/<int:id>',views.popup_delete, name='popup_delete'),
    path('investor/popup-active/<int:id>',views.popup_active, name='popup_active'),
    path('investor/popup-deactiva/<int:id>',views.popup_deactive, name='popup_deactive'),
    path('investor/send-email/',views.send_bulk_email, name='send_bulk_email'),
    path('investor/investor-pending-payment/<int:id>',views.investor_pending_payment, name='investor_pending_payment'),
    path('investor/investor-widthdraw-all/<int:id>',views.investor_widthdraw_all, name='investor_widthdraw_all'),
    path('investor/invest-all-balance/<int:id>',views.invest_all_balance, name='invest_all_balance'),
    path('investor/investor-widthdraw-interest/<int:id>',views.investor_widthdraw_interest, name='investor_widthdraw_interest'),
    path('investor/website/terms-condition',views.terms_condition, name='terms_condition'),
    path('investor/website/dashboard-terms-condition',views.dashboard_terms_condition, name='dashboard_terms_condition'),
    path('investor/website/add-terms-condition',views.add_terms_condition, name='add_terms_condition'),
    path('investor/website/update-terms-condition/<int:id>',views.update_terms_condition, name='update_terms_condition'),
    path('investor/interest/add-interest',views.add_interest, name='add_interest'),
    path('investor/interest/interest-list',views.interest_list, name='interest_list'),
    path('investor/users/add-user/',views.add_user, name='add_user'),
    path('investor/users/user-list/',views.user_list, name='user_list'),
    path('investor/edit-user/<int:id>',views.edit_user, name='edit_user'),
    path('investor/delete-user/<int:id>',views.user_delete, name='user_delete'),
    path('investor/user-login/',views.user_login, name='user_login'),
    path('investor/user/<int:id>/active-account/password-set/',views.active_user, name='active_user'),
    path('investor/user/password-reset/',views.user_password_resets, name='user_password_resets'),
    path('investor/user-password/<int:id>/reset',views.user_password_reset_link, name='user_password_reset_link'),
    path('investor/role/role-list',views.role_list, name='role_list'),
    path('investor/role/add-role',views.add_role, name='add_role'),
    path('investor/role/edit-role/<int:id>',views.edit_role, name='edit_role'),
    path('investor/user-logout',views.user_logout, name='user_logout'),

]

pfa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('investor.urls', namespace='investor'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/dashboard/all_investor_list.html
{% extends 'dashboard/base/base.html' %}
{% load extra_tags %}
{% load humanize %}
{% block d-title %}
    Investor List
{% endblock d-title %} 

{% block d-content %} 

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12"> 
          <h1 class="m-0 text-dark float-left w-75">Investor List</h1> 
          <a href="{% url 'investor:send_bulk_email' %}" class="btn btn-success float-right text-right">Send Bulk Email</a>
        </div> 
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div> 
<section class="invest_request_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <p class="float-left mb-1" style="color: red;">{{message}}</p>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered table-striped text-center">
                    <thead class="table-dark">
                        <th>SL</th>
                        <th>Full Name</th> 
                        <th>Email Address</th>
                        <th>Phone</th>
                        <th style="width: 15%;">Address</th>
                        <th style="width: 15%;">Bank Name</th>
                        <th>Bank Account</th> 
                        <th>Amount</th> 
                        <th style="width:12%">Action</th>
                    </thead>
                    <tbody>
                        
                        {% for investor in investor_list %}
                            <tr>
                                <td class="align-middle">{{forloop.counter}}</td>
                                <td class="align-middle pr-2 pl-2">{{investor.first_name}} {{investor.last_name}}</td>
                                <td class="align-middle pr-2 pl-2">{{investor.email}}</td>
                                <td class="align-middle pr-2 pl-2">{{investor.phone}}</td>
                                <td class="align-middle pr-2 pl-2">{{investor.address}}</td>
                                <td class="align-middle pr-2 pl-2">{{investor.bank_name}}</td>
                                <td class="align-middle pr-2 pl-2">{{investor.account_number}}</td>  
                                <td class="align-middle pr-2 pl-2">₦{{investor.id|investor_invest_amount}}</td>
                                <td class="align-middle pr-2 pl-2">  
                                    <div class="modal fade" id="investor-{{investor.id}}" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content"> 
                                            <div class="modal-body">
                                                <p>Are you sure you want to delete <strong>{{investor.first_name}} {{investor.last_name}}</strong> </p>  
                                                <hr>
                                                <a href="{% url 'investor:investor_delete' investor.id %}" class="btn btn-sm btn-info mr-3 pr-3 pl-3">Yes</a>
                                                <button type="button" data-dismiss="modal" class="btn btn-info btn-sm pr-3 pl-3">No</button>
                                            </div>
                                            </div>
                                        </div>
                                    </div>  
                                    <button class="btn btn-sm btn-info mr-1 mb-1" data-toggle="modal" data-target="#investor-{{investor.id}}">
                                        <i class="far fa-trash-alt"></i>
                                      </button> 
                                    <a href="{% url 'investor:admin_chat' investor.id  %}" class="btn btn-sm btn-info mb-1">Message</a>
                                </td>
                            </tr>
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section> 
{% endblock d-content %} 
{% block d-script %}
    <script> 
    </script>

{% endblock d-script %}

templates/dashboard/bank_list.html
{% extends 'dashboard/base/base.html' %}
{% load extra_tags %}
{% load humanize %}
{% block d-title %}
    Bank List
{% endblock d-title %} 

{% block d-content %} 

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12"> 
          <h1 class="m-0 text-dark float-left w-75">Bank List</h1> 
          <a href="{% url 'investor:add_bank' %}" class="btn btn-success float-right text-right">Add New Bank</a>
        </div> 
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div> 
<section class="invest_request_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <p class="float-left mb-1" style="color: red;">{{message}}</p>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered table-striped text-center">
                    <thead class="table-dark">
                        <th>SL</th>
                        <th>Bank Name</th> 
                        <th>Status</th> 
                        <th>Action</th>
                    </thead>
                    <tbody class="text-center">
                        
                        {% for bank in bank_list %}
                            <tr>
                                <td class="align-middle">{{forloop.counter}}</td>
                                <td class="align-middle">{{bank.bank_name}}</td>
                                <td class="align-middle"> 
                                    {% if bank.status %}
                                        <span>Active</span>
                                    {% else %}
                                        <span style="color: red;">Inactive</span>
                                    {% endif %} 
                                </td>
                                <td class="align-middle text-center">
                                    <a href="{% url 'investor:bank_edit' bank.id %}" class="btn btn-success btn-sm d-inline-block mr-1">Edit</a>
                                    
                                    {% if not bank.status %}
                                        <a href="{% url 'investor:bank_active' bank.id %}" class="btn btn-warning btn-sm d-inline-block mr-1">Active</a>
                                        {% else %}
                                        <a href="{% url 'investor:bank_deactive' bank.id %}" class="btn btn-success btn-sm d-inline-block mr-1">Deactive</a>
                                    {% endif %} 
                                    
                                </td> 
                                 
                            </tr>
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section> 
{% endblock d-content %} 
{% block d-script %}
    <script> 
    </script>

{% endblock d-script %}

templates/dashboard/dashboard_terms_condition.html
{% extends 'dashboard/base/base.html' %}
{% load extra_tags %}
{% load humanize %}
{% block d-title %}
    Terms & Conditions
{% endblock d-title %} 

{% block d-content %} 

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-md-9 col-sm-12"> 
          <h5 class="m-0 text-dark float-left">Terms & Condition Page</h5>  
        </div> 
        <div class="col-md-2 text-right col-sm-12"> 
            <a href="{% url 'investor:update_terms_condition' terms_conditons.id %}" class="btn btn-info float-right btn-sm">Edit Page</a>
        </div> 
            
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div> 
<section class="invest_request_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-11 col-sm-12">
                <div class="card"> 
                    <div class="card-body"> 
                            {{terms_conditons.page_content|safe}} 
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 
{% endblock d-content %} 

templates/dashboard/investor_notification_list.html
{% extends 'dashboard/base/base.html' %}
{% load extra_tags %}
{% load humanize %}
{% block d-title %}
    Notifications List
{% endblock d-title %} 

{% block d-content %} 

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-8"> 
          <h1 class="m-0 text-dark">Notification List</h1> 
        </div> 
        <div class="col-3"> 
            {% if investor_notifications %}
            <a href="{% url 'investor:investor_unread_notification_list' request.session.investor %}" class="btn btn-info float-right btn-sm">Unread Notifications</a>
            {% elif investor_unread_notifications %}
                <a href="{% url 'investor:investor_notification_list' request.session.investor %}" class="btn btn-info float-right btn-sm mr-1">All Notifications</a>
            {% endif %}
        </div> 
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div> 
<section class="invest_request_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-11 col-sm-12">
                <div class="card card-body">  
                <p id="delete" style="color: red;"></p>
                {% if investor_notifications %}  
                    {% for notification in investor_notifications %} 
                    {% if not notification.is_view %}
                        <div class="little_shadow notification alert text-dark alert-dismissible fade show no-border alert-light m-0" role="alert">
                    {% else %}
                        <div class="text-dark notification alert alert-dismissible fade show no-border alert-light m-0" role="alert">
                    {% endif %} 
                    
                        <button onclick="deleteNotification({{notification.id}})" type="button" class="text-dark close color-white" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <a class="text-dark" href="{% url 'investor:single_nofication' notification.id %}"> 
                            <p class="card-desc mb-0">{{notification.title|safe}}</p>
                            <span class="m-0 text-sm">{{notification.date|naturaltime}}</span> 
                        </a>
                    </div> 
                    {% endfor %}  

                    {% if investor_notifications.has_other_pages %}
                        <nav class="mt-3 float-right" aria-label="Page navigation example">
                            <ul class="pagination float-right">
                            {% if investor_notifications.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ investor_notifications.previous_page_number }}">Previous</a></li>
                            {% else %}
                                <li class="disabled page-item"><span class="page-link">Previous</span></li>
                            {% endif %}
                            {% for i in investor_notifications.paginator.page_range %}
                                {% if investor_notifications.number == i %}
                                <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only page-link">(current)</span></span></li>
                                {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if investor_notifications.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ users.next_page_number }}">Next</a></li>
                            {% else %}
                                <li class="disabled page-item"><span class="page-link">Next</span></li>
                            {% endif %}
                            </ul>
                        </nav>
                    {% endif %}


                        
                {% elif investor_unread_notifications %}  
                    {% for notification in investor_unread_notifications %} 
                    <div class="little_shadow notification alert alert-dismissible fade show no-border alert-light m-0" role="alert">
                        <button  onclick="markAsRead({{notification.id}})" type="button" class="text-dark close color-white" data-dismiss="alert" aria-label="Close">
                            <span style="font-size:12px" aria-hidden="true">Mark As Read</span>
                        </button>
                        <a class="text-dark" href="{% url 'investor:single_nofication' notification.id %}"> 
                            <p class="card-desc mb-0">{{notification.title|safe}}</p>
                            <span class="m-0 text-sm">{{notification.date|naturaltime}}</span> 
                        </a>
                    </div>
                    <h4 id="no_data"></h4>
                    {% endfor %}
                    
                    {% if investor_unread_notifications.has_other_pages %}
                    <nav class="mt-3 float-right" aria-label="Page navigation example">
                        <ul class="pagination float-right">
                        {% if investor_unread_notifications.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ investor_unread_notifications.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">Previous</span></li>
                        {% endif %}
                        {% for i in investor_unread_notifications.paginator.page_range %}
                            {% if investor_unread_notifications.number == i %}
                            <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only page-link">(current)</span></span></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if investor_unread_notifications.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ users.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">Next</span></li>
                        {% endif %}
                        </ul>
                    </nav>
                {% endif %} 

                {% else %}
                    <h4>There is no Notifications</h4>
                        
                {% endif %} 
                    
                </div>
            </div>
        </div>
    </div>
</section> 
{% endblock d-content %} 
{% block d-script %}
    <script>

        function deleteNotification(id){ 
            $.ajax({
                url:"{% url 'investor:ajax_notification_delete' %}",
                type:'get',
                data:{
                    notification_id: id
                }, 
                success:function(response){   
                    document.getElementById("delete").innerHTML = "Item Deleted Successfully"
                },
                error:function(response){
                  alert("Something is missing")
                }
              });
          }
        function markAsRead(id){ 

            var value = document.getElementById("adnt").getAttribute('data-value');
            var new_val = value - 1
            if(new_val > 0){
                document.getElementById("adnt").innerHTML = new_val
                document.getElementById("adnt").setAttribute('data-value',new_val)
            }
            else{
                document.getElementById("adnt").innerHTML = ""
                document.getElementById("adnt").setAttribute('data-value',"") 
                document.getElementById("no_data").innerHTML = "No new notification"
            } 

            $.ajax({
                url:"{% url 'investor:ajax_notification_markas_read' %}",
                type:'get',
                data:{
                    notification_id: id
                }, 
                success:function(response){   
                    document.getElementById("delete").innerHTML = "Marked As Read"
                },
                error:function(response){
                  alert("Something is missing")
                }
              });
          }


    </script>

{% endblock d-script %}

templates/dashboard/nofication_details.html
{% extends 'dashboard/base/base.html' %}
{% load extra_tags %}
{% load humanize %}
{% block d-title %}
    Notification Details
{% endblock d-title %} 

{% block d-content %} 

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-md-9 col-sm-12"> 
          <h5 class="m-0 text-dark float-left">{{notification.title|safe}}</h5>  
        </div> 
        <div class="col-md-3 col-sm-12">  
          
          {% if request.user.is_authenticated %}
            <a href="{% url 'investor:admin_notification_list' %}" class="btn btn-info float-left btn-sm mr-1">All Notifications</a>
            <a href="{% url 'investor:admin_unread_notifications' %}" class="btn btn-info float-left btn-sm">Unread Notifications</a>
          {% elif request.session.investor %}
            <a href="{% url 'investor:investor_notification_list' request.session.investor %}" class="btn btn-info float-left btn-sm mr-1">All Notifications</a>
            <a href="{% url 'investor:investor_unread_notification_list' request.session.investor %}" class="btn btn-info float-left btn-sm">Unread Notifications</a>
          {% endif %}
            
          
        </div> 
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div> 
<section class="invest_request_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-11 col-sm-12">
                <div class="card"> 
                    <div class="card-body">
                        <p class="card-desc">{{notification.desc|safe}}</p>
                        {% if notification.has_download %}
                          <p>Click <a target="_blank" href="{% url 'investor:terms_condition_pdf' request.session.investor %}">HERE</a> to download your post-payment contract.
                          </p>
                        {% endif %}
                        <span class="m-0 text-muted text-sm">{{notification.date|naturaltime}}</span> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 
{% endblock d-content %} 

templates/dashboard/popup_list.html
{% extends 'dashboard/base/base.html' %}
{% load extra_tags %}
{% load humanize %}
{% block d-title %}
    Popup List
{% endblock d-title %} 

{% block d-content %} 

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12"> 
          <h1 class="m-0 text-dark float-left w-75">PopUp List</h1> 
          <a href="{% url 'investor:add_popup' %}" class="btn btn-success float-right text-right">Add New PopUp</a>
        </div> 
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div> 
<section class="invest_request_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <p class="float-left mb-1" style="color: red;">{{message}}</p>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered table-striped text-center">
                    <thead class="table-dark">
                        <th>SL</th>
                        <th>Title</th> 
                        <th>Description</th> 
                        <th>Status</th>
                        <th>Action</th>
                    </thead>
                    <tbody class="text-center">
                        
                        {% for popup in popup_list %}
                            <tr>
                                <td class="align-middle">{{forloop.counter}}</td>
                                <td class="align-middle">{{popup.title|truncatechars:30}}</td>
                                <td class="align-middle">{{popup.desc|truncatechars:40}}</td>
                                <td class="align-middle"> 
                                    {% if popup.status %}
                                        <span>Active</span>
                                    {% else %}
                                        <span style="color: red;">Inactive</span>
                                    {% endif %} 
                                </td>
                                <td style="width:20%" class="align-middle text-center">


                                    <div class="modal fade" id="popup-{{popup.id}}" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content"> 
                                            <div class="modal-body">
                                                <p>Are you sure you want to delete this Popup </p>  
                                                <hr>
                                                <a href="{% url 'investor:popup_delete' popup.id %}" class="btn btn-sm btn-info mr-3 pr-3 pl-3">Yes</a>
                                                <button type="button" data-dismiss="modal" class="btn btn-info btn-sm pr-3 pl-3">No</button>
                                            </div>
                                            </div>
                                        </div>
                                    </div>  
                                    <a href="{% url 'investor:popup_edit' popup.id %}" class="btn btn-success btn-sm d-inline-block mr-1">Edit</a>
                                    <button class="btn btn-sm btn-danger mr-1" data-toggle="modal" data-target="#popup-{{popup.id}}">Delete</button>                                    
                                    {% if not popup.status %}
                                        <a href="{% url 'investor:popup_active' popup.id %}" class="btn btn-warning btn-sm d-inline-block mr-1">Active</a>
                                        {% else %}
                                        <a href="{% url 'investor:popup_deactive' popup.id %}" class="btn btn-success btn-sm d-inline-block mr-1">Deactive</a>
                                    {% endif %} 
                                    
                                </td> 
                                 
                            </tr>
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section> 
{% endblock d-content %} 
{% block d-script %}
    <script> 
    </script>

{% endblock d-script %}