investor/urls.py
from django.urls import path 
from . import views
app_name = 'investor'
urlpatterns = [
    path('investor/admin/login', views.admin_login, name="admin_login"),
    path('investor/admin/logout', views.admin_logout, name="admin_logout"), 
    path('dashboards/', views.dashboard, name='dashboard'),
    path('investor/signup',views.investor_registration, name='investor_registration'),
    path('',views.investor_login, name='investor_login'),
    path('investor/password-reset',views.investor_password_resets, name='investor_password_resets'),
    path('investor-account/<int:id>/active',views.investor_account_active, name='investor_account_active'),
    path('investor-password/<int:id>/reset',views.investor_password_reset_link, name='investor_password_reset_link'),
    path('investor/logout',views.investor_logout, name='investor_logout'),
    path('investor/request_to_invest/<int:id>/',views.request_to_invest, name='request_to_invest'),
    path('admin/approve/<int:id>/',views.approve_investment, name='approve_investment'),
    path('admin/cancle/<int:id>/',views.cancle_investment, name='cancle_investment'),
    path('admin/notifications/',views.admin_notification_list, name='admin_notification_list'),
    path('admin/notifications/unread',views.admin_unread_notifications, name='admin_unread_notifications'),
    path('admin/notifications/<int:id>/',views.investor_notification_list, name='investor_notification_list'),
    path('admin/notifications/unread/<int:id>/',views.investor_unread_notification_list, name='investor_unread_notification_list'),
    path('investor/notification/<int:id>/',views.single_nofication, name='single_nofication'),
    path('investor/notification/delete',views.ajax_notification_delete, name='ajax_notification_delete'),
    path('investor/notification/mark-read',views.ajax_notification_markas_read, name='ajax_notification_markas_read'),
    path('investor/<int:id>/terms-condition-pdf',views.terms_condition_pdf, name='terms_condition_pdf'),
    path('investor/investors/investors-list/',views.all_investor_list, name='all_investor_list'),
    path('investor/investor/<int:id>/delete',views.investor_delete, name='investor_delete'),
    path('investor/invests/all-pending-request',views.all_pending_request, name='all_pending_request'),
    path('investor/invests/all-active-invest-list',views.all_active_invest_list, name='all_active_invest_list'),
    path('investor/payments/upcoming-payment',views.upcoming_payment, name='upcoming_payment'),
    path('investor/admin-chat/<int:id>',views.admin_chat, name='admin_chat'),
    path('investor/investor-chat/<int:id>',views.investor_chat, name='investor_chat'),
    path('investor/make-payment/<int:id>',views.make_payment, name='make_payment'),
    path('investor/payments/interest-paid-admin',views.interest_paid_admin, name='interest_paid_admin'),
    path('investor/interest-paid/<int:id>/delete',views.interest_paid_admin_delete, name='interest_paid_admin_delete'),
    path('investor/dashboard/password/change',views.admin_password_change, name='admin_password_change'),
    path('investor/investors/add-investor/',views.add_new_investor, name='add_new_investor'),
    path('investor-active-link/<int:id>/activate',views.investor_active_link, name='investor_active_link'),
    path('investor/banks/add-bank',views.add_bank, name='add_bank'),
    path('investor/banks/bank-list',views.bank_list, name='bank_list'),
    path('investor/bank-list/<int:id>',views.bank_edit, name='bank_edit'),
    path('investor/bank-active/<int:id>',views.bank_active, name='bank_active'),
    path('investor/bank-deactive/<int:id>',views.bank_deactive, name='bank_deactive'),
    path('investor/password-change/<int:id>',views.investor_password_change, name='investor_password_change'),
    path('investor/profile-update/<int:id>',views.investor_profile_update, name='investor_profile_update'),
    path('investor/interest-received-investor/<int:id>',views.interest_received_investor, name='interest_received_investor'),
    path('investor/investor-active-invest/<int:id>',views.investor_active_invest, name='investor_active_invest'),
    path('investor/investor-pending-invest/<int:id>',views.investor_pending_invest, name='investor_pending_invest'),
    path('investor/investor-cancle-invest/<int:id>',views.investor_cancle_investment, name='investor_cancle_investment'),
    path('investor/popup/add-popup',views.add_popup, name='add_popup'),
    path('investor/popup/popup-list',views.popup_list, name='popup_list'),
    path('investor/popup/popup-edit/<int:id>',views.popup_edit, name='popup_edit'),
    path('investor/popup-delete/<int:id>',views.popup_delete, name='popup_delete'),
    path('investor/popup-active/<int:id>',views.popup_active, name='popup_active'),
    path('investor/popup-deactiva/<int:id>',views.popup_deactive, name='popup_deactive'),
    path('investor/send-email/',views.send_bulk_email, name='send_bulk_email'),
    path('investor/investor-pending-payment/<int:id>',views.investor_pending_payment, name='investor_pending_payment'),
    path('investor/investor-widthdraw-all/<int:id>',views.investor_widthdraw_all, name='investor_widthdraw_all'),
    path('investor/invest-all-balance/<int:id>',views.invest_all_balance, name='invest_all_balance'),
    path('investor/investor-widthdraw-interest/<int:id>',views.investor_widthdraw_interest, name='investor_widthdraw_interest'),
    path('investor/website/terms-condition',views.terms_condition, name='terms_condition'),
    path('investor/website/dashboard-terms-condition',views.dashboard_terms_condition, name='dashboard_terms_condition'),
    path('investor/website/add-terms-condition',views.add_terms_condition, name='add_terms_condition'),
    path('investor/website/update-terms-condition/<int:id>',views.update_terms_condition, name='update_terms_condition'),
    path('investor/interest/add-interest',views.add_interest, name='add_interest'),
    path('investor/interest/interest-list',views.interest_list, name='interest_list'),
    path('investor/users/add-user/',views.add_user, name='add_user'),
    path('investor/users/user-list/',views.user_list, name='user_list'),
    path('investor/edit-user/<int:id>',views.edit_user, name='edit_user'),
    path('investor/delete-user/<int:id>',views.user_delete, name='user_delete'),
    path('investor/user-login/',views.user_login, name='user_login'),
    path('investor/user/<int:id>/active-account/password-set/',views.active_user, name='active_user'),
    path('investor/user/password-reset/',views.user_password_resets, name='user_password_resets'),
    path('investor/user-password/<int:id>/reset',views.user_password_reset_link, name='user_password_reset_link'),
    path('investor/role/role-list',views.role_list, name='role_list'),
    path('investor/role/add-role',views.add_role, name='add_role'),
    path('investor/role/edit-role/<int:id>',views.edit_role, name='edit_role'),
    path('investor/user-logout',views.user_logout, name='user_logout'),

]

pfa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('investor.urls', namespace='investor'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/dashboard/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>
  {% block d-title %}
    
  {% endblock d-title %}
    </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static '/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <!-- Tempusdominus Bbootstrap 4 --> 
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static '/dist/css/adminlte.min.css' %}"> 
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static '/css/dashboard.css' %}">
<style>
  #loaders{
    width:100%;
    height: 100%;
    background-color: #ddd;
    position: absolute;
    top: 0;
    left: 0;
    text-align: center;
    z-index: 99999;
    padding-top: 200px;
    justify-content: center;
    display: flex;
  }
</style>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <div id="loaders">
    <div class="spinner-border text-center" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>

  <!-- Navbar -->
  {% include 'dashboard/base/top_menu.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'dashboard/base/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper"> 
    
    {% block d-content %}
      
    {% endblock d-content %}
      
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2021 Cashy Investment</strong>
    All rights reserved. 
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static '/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->  
<!-- Bootstrap 4 -->
<script src="{% static '/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<!-- AdminLTE App -->
<script src="{% static '/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static '/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->

{% block d-script %}

{% endblock d-script %}
<script> 
  $(window).on("load", function(){
    $("#loaders").fadeOut(1000);
  })
</script>
</body>
</html>

templates/dashboard/base/top_menu.html
{% load extra_tags %}
{% load humanize %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'investor:dashboard' %}" class="nav-link">Dashboard</a>
      </li>
      
      {% if request.user.is_authenticated %}
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'investor:admin_logout' %}" class="nav-link">Log out</a>
        </li>
      {% elif request.session.investor %}
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'investor:investor_logout' %}" class="nav-link">Log out</a>
        </li>
      {% elif request.session.editor %}
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'investor:user_logout' %}" class="nav-link">Log out</a>
        </li>
      {% endif %}  
      
      {% if request.session.investor %}
        
      <li class="nav-item d-none d-sm-inline-block">
        <a class="btn btn-info btn-sm mt-1" href="{% url 'investor:request_to_invest' request.session.investor %}" class="nav-link">Request to Invest</a>
      </li>
        
      {% endif %}
    </ul>  
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->

      {% if request.user.is_authenticated or request.session.editor %}
        {% if request.user.is_authenticated or request.session.editor|user_has_access:"Inbox"%}
        <li class="nav-item dropdown">
          <a class="nav-link" href="{% url 'investor:admin_chat' 0 %}">
            <i class="far fa-comments"></i> 
              {% if admin_message|show_unread_admin_message %}
              <span class="badge badge-danger navbar-badge"> {{admin_message|show_unread_admin_message }}</span>
              {% endif %}  
          </a> 
        </li>
        {% endif %}
      {% elif request.session.investor %}
        <li class="nav-item dropdown">
          <a class="nav-link" href="{% url 'investor:investor_chat' request.session.investor  %}">
            <i class="far fa-comments"></i> 
              {% if request.session.investor|show_unread_investor_message %}
              <span class="badge badge-danger navbar-badge"> {{request.session.investor|show_unread_investor_message }}</span>
              {% endif %}  
          </a> 
        </li>
      {% endif %}  
 
      
      <!-- Notifications Dropdown Menu -->
      {% if request.user.is_authenticated or request.session.editor %} 

      {% if request.user.is_authenticated or request.session.editor|user_has_access:"Notification"%}

      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>  
            <span class="badge badge-warning navbar-badge" id="adnt" data-value="{{admin_notification|admin_notifications}}">{{admin_notification|admin_notifications}}</span> 
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right notification_button"> 
          <span class="dropdown-item dropdown-header">{{admin_notification|admin_notifications}} Notifications</span> 
          
          {% for item in admin_notification|admin_notification_list %}
          <div class="border-top alert alert-dismissible fade show no-border my_notification" role="alert">
            <button type="button" class="close color-white" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <a class="text-muted" href="{% url 'investor:single_nofication' item.id %}">{{item.title|safe}}</a> 
            <span class="m-0 text-muted text-sm">{{item.date|naturaltime}}</span>
          </div> 
            
          {% endfor %} 
          <div class="dropdown-divider"></div>
          <a href="{% url 'investor:admin_unread_notifications' %}" class="dropdown-item dropdown-footer">New Notifications</a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'investor:admin_notification_list' %}" class="dropdown-item dropdown-footer">All Notifications</a>
        </div>
      </li>
      {% endif %}

      {% elif request.session.investor %}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>  
            <span class="badge badge-warning navbar-badge" id="adnt" data-value="{{request.session.investor|investor_notifications}}">{{request.session.investor|investor_notifications}}</span> 
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right notification_button"> 
          <span class="dropdown-item dropdown-header">{{request.session.investor|investor_notifications}} Notifications</span> 
          
          {% for item in request.session.investor|investor_notification_list %}
          <div class="border-top alert alert-dismissible fade show no-border my_notification" role="alert">
            <button type="button" class="close color-white" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <a class="text-muted" href="{% url 'investor:single_nofication' item.id %}">{{item.title|safe}}</a> 
            <span class="m-0 text-muted text-sm">{{item.date|naturaltime}}</span>
          </div> 
            
          {% endfor %}
             

          <div class="dropdown-divider"></div>
            <a href="{% url 'investor:investor_unread_notification_list' request.session.investor %}" class="dropdown-item dropdown-footer">New Notifications</a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'investor:investor_notification_list' request.session.investor %}" class="dropdown-item dropdown-footer">All Notifications</a>
        </div>
      </li>
      {% endif %}
      <li class="nav-item mr-4">
         
      </li>
    </ul>
  </nav>